# Travis CI Build configuration
# See https://config.travis-ci.com/ for reference.

branches:
  only:
  - master

jobs:
  include:
  - stage: lint
    language: go
    go:
    - "1.13"
    script: make lint

  - stage: test-and-coverage
    language: go
    go:
    - "1.13"
    script:
    - make test cov/coverage.txt
    - bash <(curl -s https://codecov.io/bash)
