# Travis CI Build configuration
# See https://config.travis-ci.com/ for reference.

# only affects "push to branch" trigger, "pull request" trigger still builds other branches
branches:
  only:
  - master

jobs:
  include:
  - stage: Lint, test and coverage
    language: go
    go:
    - "1.13"
    script:
    - make lint test cov/coverage.txt
    - bash <(curl -s https://codecov.io/bash)
