jobs:
  include:
  - language: go
    go:
    - "1.13"
    stage: lint
    script: make lint

  - language: go
    go:
    - "1.13"
    stage: test
    script: make test
    after_success: bash <(curl -s https://codecov.io/bash)
