jobs:
  include:
  - stage: lint
    language: go
    go:
    - "1.13"
    script: make lint

  - stage: test-and-coverage
    language: go
    go:
    - "1.13"
    script:
    - make test cov/coverage.txt
    - bash <(curl -s https://codecov.io/bash)

  - stage: build-and-release
    branches:
      only:
      - master
    script: curl -X POST $DOCKER_BUILD_URL
