jobs:
  include:
  - language: go
    go:
    - "1.13"
    stage: lint
    script: make lint

  - language: go
    go:
    - "1.13"
    stage: test-and-coverage
    script:
    - make test cov/coverage.txt
    - bash <(curl -s https://codecov.io/bash)

  - stage: build-and-release
    script: curl -X POST $DOCKER_BUILD_URL
