language: go
go:
- "1.13"
sudo: false
jobs:
  include:
  - stage: lint
    install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
      sh -s -- -b $(go env GOPATH)/bin v1.18.0
    script: make lint
  - stage: test
    script: make test
